import test from 'node:test';
import assert from 'node:assert/strict';
import {api} from '../worker/api.mjs';
import {localDatabase} from '../scripts/local-db.mjs';
import {freshRace,tickRace,replayRace,RACE_POINTS,COSTS,normalisePoints} from '../dist/planet/expedition.mjs';
function client(db,owner){return async(path,data,method=data?'POST':'GET')=>{const headers={'Content-Type':'application/json',Origin:'https://boia.test'};if(owner)headers['oai-authenticated-user-id']=owner;const r=await api(new Request('https://boia.test/api/'+path,{method,headers,...(data?{body:JSON.stringify(data)}:{})}),{DB:db});return {status:r.status,data:await r.json()};};}
test('public readers need no account; private writes require identity and consent',async()=>{const db=localDatabase(),guest=client(db),owner=client(db,'test-a');try{assert.equal((await guest('session')).data.authenticated,false);assert.equal((await guest('profile',{nickname:'QA'})).status,401);assert.equal((await owner('profile',{nickname:'QA'})).status,400);assert.equal((await owner('profile',{nickname:'QA',publicConsent:true})).status,200);assert.equal((await guest('leaderboard')).data.rows.length,1);}finally{db.close();}});
test('bottles enforce 140 characters, one per owner and removal ownership',async()=>{const db=localDatabase(),a=client(db,'a'),b=client(db,'b');try{for(const [c,nickname] of [[a,'Sailor A'],[b,'Sailor B']])await c('profile',{nickname,publicConsent:true});assert.equal((await a('bottles',{body:'x'.repeat(141),x:0,z:41})).status,400);const first=await a('bottles',{body:'Hello sea',x:0,z:41});const second=await a('bottles',{body:'Updated voyage',x:3,z:40});assert.equal(first.data.id,second.data.id);assert.equal((await a('bottles')).data.bottles.length,1);await b('bottles',{},'DELETE');assert.equal((await b('bottles')).data.bottles.length,1);await a('bottles',{},'DELETE');assert.equal((await b('bottles')).data.bottles.length,0);}finally{db.close();}});
test('shared progress recomputes points, deduplicates rewards and keeps surveys private',async()=>{const db=localDatabase(),a=client(db,'a'),guest=client(db);try{const p=(await a('profile',{nickname:'Test sailor',publicConsent:true})).data.profile;const data={points:999999,coins:999999,rewards:['find-history','find-history','constructor','bottle','first-race'],owned:['flag'],discovered:['history','fake-island'],survey:{next:'Test artist'}};const r=(await a('progress',data)).data.profile;assert.equal(r.points,20);assert.equal(r.coins,20);assert.deepEqual(r.owned,[]);assert.deepEqual(r.discovered,['history']);assert.equal(r.survey.next,'Test artist');assert.equal((await guest('profiles/'+p.id)).data.survey,undefined);const r2=(await a('progress',{...data,rewards:['find-history','find-music'],owned:['flag']})).data.profile;assert.equal(r2.points,40);assert.equal(r2.coins,0);assert.deepEqual(r2.owned,['flag']);}finally{db.close();}});
test('race replay requires the full route and cannot accept a claimed finish time',async()=>{const db=localDatabase(),a=client(db,'a');try{await a('profile',{nickname:'Test racer',publicConsent:true});const start=await a('race/start',{});assert.equal((await a('race/finish',{id:start.data.id,timeMs:1,commands:[[1,0,0,null]]})).status,400);assert.deepEqual((await a('leaderboard?type=race')).data.rows,[]);const s=freshRace(),trace=[];for(let i=0;i<15000&&!s.finished;i++){const next=RACE_POINTS[s.checkpoint],heading=Math.atan2(next.x-s.x,next.z-s.z);const cmd=[1,0,0,heading];trace.push(cmd);tickRace(s,cmd);}assert.equal(s.finished,true);const replay=replayRace(trace);assert.equal(replay.valid,true);assert.equal(replay.ticks,s.ticks);assert.ok(replay.timeMs>10000&&replay.timeMs<180000);await db.prepare('UPDATE race_runs SET created_at=? WHERE id=?').bind(Date.now()-replay.timeMs-4000,start.data.id).run();const finished=await a('race/finish',{id:start.data.id,commands:trace});assert.equal(finished.status,200);assert.equal(finished.data.profile.points,40);const duplicate=await a('race/finish',{id:start.data.id,commands:trace});assert.equal(duplicate.data.alreadySaved,true);const rank=(await a('leaderboard?type=race')).data;assert.equal(rank.rows.length,1);assert.equal(rank.rows[0].timeMs,replay.timeMs);assert.equal(rank.me.position,1);}finally{db.close();}});
