import test from 'node:test';
import assert from 'node:assert/strict';
import * as T from '../dist/three.module.min.js';
import {LivingSea} from '../dist/planet/living-sea.mjs';
import {mergeSea,seaScore,missionMerge,arrived,addSeaFind} from '../dist/planet/adventure.mjs';
import {freshRace,tickRace,gateTargets,replayRace,normalisePoints,ROCKS,JELLIES} from '../dist/planet/expedition.mjs';
import {ARTISTS,artistTrio} from '../dist/planet/content-data.mjs';
import {EVENTS,initialProgress} from '../dist/planet/model.mjs';
import {api} from '../worker/api.mjs';
import {localDatabase} from '../scripts/local-db.mjs';
function rig(){return {world:new T.Group(),boat:{g:new T.Group()},s:{x:11,z:-33,vx:0,vz:0},onLife:null};}
test('rescue is physical, restores aboard, delivers once and empties the boat',()=>{const w=rig(),life=new LivingSea(w),events=[];w.onLife=e=>events.push(e);life.rescue();assert.equal(life.state,'aboard');for(let i=0;i<100;i++)life.tick(.02,i*.02,true);assert.equal(life.mascot.parent,w.boat.g);assert.equal(events.filter(e=>e.type==='rescued').length,1);life.rescue();assert.equal(events.filter(e=>e.type==='rescued').length,1);const restored=new LivingSea(rig());restored.setProgress({mission:'aboard'});assert.equal(restored.mascot.parent,restored.w.boat.g);w.s.x=-2;w.s.z=-222;for(let i=0;i<200;i++)life.tick(.02,4+i*.02,true);assert.equal(life.state,'delivered');assert.equal(life.mascot.parent,life.group);assert.equal(events.filter(e=>e.type==='delivered').length,1);life.setProgress({mission:'lost'});assert.equal(life.state,'delivered');assert.ok(life.mascot.position.z<-229);});
test('sea ledger survives offline merging without double-credit; wood actually respawns',()=>{const p=initialProgress();addSeaFind(p,'device-111','wood',3);const merged=mergeSea(p.seaLedger,{'device-111':{wood:2},'device-222':{chest:1}});assert.equal(seaScore(merged),27);assert.deepEqual(mergeSea(merged,merged),merged);normalisePoints({...p,seaLedger:merged,points:999999});const w=rig(),l=new LivingSea(w),found=[];w.onLife=e=>found.push(e);const f=l.woods[0];w.s.x=f.mesh.position.x;w.s.z=f.mesh.position.z;l.tick(.02,1,true);assert.equal(f.mesh.visible,false);assert.equal(found[0].kind,'wood');w.s.x=0;w.s.z=60;for(let i=0;i<2900;i++)l.tick(.02,i*.02,true);assert.equal(f.mesh.visible,true);});
test('all island shores can trigger arrival; inner land is not required',()=>{for(const ev of EVENTS)for(let angle=0;angle<Math.PI*2;angle+=Math.PI/8){assert.equal(arrived({x:ev.x+Math.cos(angle)*(ev.r+5),z:ev.z+Math.sin(angle)*(ev.r+5)},ev),true);}assert.equal(arrived({x:90,z:60},EVENTS[0]),false);});
test('both race routes finish under replay with real boosts and distinct branches',()=>{for(const shortcut of [false,true]){const s=freshRace(),trace=[];for(let i=0;i<18000&&!s.finished;i++){const next=gateTargets(s.checkpoint).at(shortcut?-1:0),cmd=[1,0,0,Math.atan2(next.x-s.x,next.z-s.z)];tickRace(s,cmd);trace.push(cmd);}assert.equal(s.finished,true);assert.equal(s.route,shortcut?'shortcut':'normal');assert.ok(s.boosts>=10);assert.equal(replayRace(trace).valid,true);assert.equal(replayRace(trace.slice(0,-15)).valid,false);}});
test('rocks bounce and jellyfish slow for a fixed duration',()=>{const s=freshRace();Object.assign(s,{x:ROCKS[0].x,z:ROCKS[0].z+.5,vz:-8,boost:0});tickRace(s,[0,0,0,null]);assert.equal(s.hit,'rock');assert.ok(s.vz>0);const jelly=freshRace();Object.assign(jelly,{x:JELLIES[0].x,z:JELLIES[0].z,boost:0});tickRace(jelly,[0,0,0,null]);assert.equal(jelly.slow,120);for(let i=0;i<121;i++)tickRace(jelly,[1,0,0,Math.PI]);assert.equal(jelly.slow,0);});
test('artist rotation covers the supplied 26 people fairly and never repeats adjacent trios',()=>{assert.equal(ARTISTS.length,26);const counts=Array(26).fill(0);let prev=[];for(let c=0;c<78;c+=3){const trio=artistTrio(c);assert.equal(new Set(trio).size,3);assert.ok(trio.every(i=>!prev.includes(i)));trio.forEach(i=>counts[i]++);prev=trio;}assert.ok(counts.every(n=>n===3));});
test('Carnet answers, mission and repeatable progress persist; bottles award nothing; purchase stamps are idempotent',async()=>{const db=localDatabase();const request=async(path,data,owner='qa',extra={})=>{const r=await api(new Request('https://boia.test/api/'+path,{method:data?'POST':'GET',headers:{'Content-Type':'application/json',...(owner?{'oai-authenticated-user-id':owner}:{}),...(extra.headers||{})},...(data?{body:JSON.stringify(data)}:{})}),{DB:db,...extra.env});return {status:r.status,data:await r.json()};};try{const p=(await request('profile',{nickname:'QA Member',publicConsent:true,answers:['rare','discovery','art','memory','dancing'],avatar:'ocean'})).data.profile;assert.equal(p.answers.length,5);assert.equal(p.avatar,'ocean');assert.ok(p.memberSince>0);const data={seaLedger:{'device-test':{wood:5}},mission:'aboard'};await request('progress',data);await request('progress',data);const state=(await request('session')).data.profile;assert.equal(state.points,15);assert.equal(state.mission,'aboard');assert.equal((await request('bottles',{body:'A free message',x:0,z:30})).data.profile.points,15);const pub=(await request('profiles/'+p.id,undefined,null)).data;assert.equal(pub.seaLedger,undefined);assert.equal(pub.answers[3],'memory');assert.equal((await request('tickets/webhook',{profileId:p.id,eventId:'halloween',purchaseId:'test-1'},null)).status,503);const extra={headers:{authorization:'Bearer qa-secret'},env:{TICKET_WEBHOOK_SECRET:'qa-secret'}};await request('tickets/webhook',{profileId:p.id,eventId:'halloween',purchaseId:'test-1'},null,extra);await request('tickets/webhook',{profileId:p.id,eventId:'halloween',purchaseId:'test-1'},null,extra);assert.equal((await request('stamps')).data.stamps.length,1);assert.equal((await request('tickets/webhook',{profileId:p.id,eventId:'newyear',purchaseId:'test-2'},null,{env:extra.env})).status,401);}finally{db.close();}});
