import test from 'node:test';
import assert from 'node:assert/strict';
import {initialProgress,grant,discover,buy,moveBoat,loadProgress,EVENTS,NODES,COLLIDERS} from '../dist/planet/model.mjs';
test('discoveries and rewards cannot be farmed by repeated visits',()=>{const p=initialProgress();assert.equal(discover(p,'music'),true);assert.equal(discover(p,'music'),false);assert.equal(grant(p,'rescue',30),true);assert.equal(grant(p,'rescue',30),false);assert.equal(p.coins,50);assert.deepEqual(p.discovered,['music']);});
test('cosmetic purchases preserve earned rank points and do not charge twice',()=>{const p=initialProgress();grant(p,'a',60);assert.equal(buy(p,'flag',40),true);assert.equal(p.coins,20);assert.equal(p.points,60);assert.equal(buy(p,'flag',40),true);assert.equal(p.coins,20);assert.equal(buy(p,'trail',60),false);assert.deepEqual(p.owned,['flag']);});
test('browser progress roundtrip retains passport, rewards and cosmetic choices',()=>{const p=initialProgress();p.nickname='Piloto QA';p.color='#20a5c3';discover(p,'history');p.flag=true;p.owned=['flag'];const s={getItem:()=>JSON.stringify(p)};assert.deepEqual(loadProgress(s),p);assert.deepEqual(loadProgress({getItem:()=>'{broken'}),initialProgress());});
test('drift increases turn rate while retaining lateral momentum',()=>{const a={x:0,z:40,heading:0,vx:0,vz:8},b={...a};for(let i=0;i<25;i++){moveBoat(a,{throttle:1,turn:1},.02,[]);moveBoat(b,{throttle:1,turn:1,drift:true},.02,[]);}assert.ok(b.heading>a.heading*1.6);const slip=s=>Math.abs(Math.atan2(s.vx,s.vz)-s.heading);assert.ok(slip(b)>slip(a));});
test('islands repel the boat and every dock remains reachable outside collisions',()=>{const first=EVENTS[0],s={x:first.x,z:first.z,heading:0,vx:0,vz:0};moveBoat(s,{},.02);assert.ok(Math.hypot(s.x-first.x,s.z-first.z)>=first.r*.9+1.39);for(const e of EVENTS)for(const o of COLLIDERS)assert.ok(Math.hypot(e.dock.x-o.x,e.dock.z-o.z)>o.r+1.4);for(const n of NODES)if(['buoy','rescue','treasure'].includes(n.kind))for(const o of COLLIDERS)assert.ok(Math.hypot(n.x-o.x,n.z-o.z)>o.r+1.4);});
test('three event islands and six collectible buoys have unique identifiers',()=>{assert.equal(EVENTS.length,3);assert.equal(NODES.filter(n=>n.kind==='buoy').length,6);const ids=[...EVENTS,...NODES].map(n=>n.id);assert.equal(new Set(ids).size,ids.length);});
