import {sqliteTable,text,integer,real,index,uniqueIndex} from 'drizzle-orm/sqlite-core';
export const profiles=sqliteTable('profiles',{
 id:text('id').primaryKey(),answers:text('answers').notNull().default('[]'),avatar:text('avatar').notNull().default('coral'),mission:text('mission').notNull().default('lost'),sea_ledger:text('sea_ledger').notNull().default('{}'),nickname:text('nickname').notNull(),genres:text('genres').notNull().default(''),artist:text('artist').notNull().default(''),memory:text('memory').notNull().default(''),message:text('message').notNull().default(''),survey:text('survey'),color:text('color').notNull().default('#ff622e'),flag:integer('flag').notNull().default(0),trail:integer('trail').notNull().default(0),model:text('model').notNull().default('classic'),accessory:integer('accessory').notNull().default(0),owned:text('owned').notNull().default('[]'),rewards:text('rewards').notNull().default('[]'),discovered:text('discovered').notNull().default('[]'),points:integer('points').notNull().default(0),coins:integer('coins').notNull().default(0),active_seconds:real('active_seconds').notNull().default(0),public_id:text('public_id').notNull(),created_at:integer('created_at').notNull(),updated_at:integer('updated_at').notNull()
},t=>[uniqueIndex('profiles_public_id').on(t.public_id),index('profiles_points').on(t.points)]);
export const bottles=sqliteTable('bottles',{owner:text('owner').primaryKey().references(()=>profiles.id),id:text('id').notNull(),body:text('body').notNull(),x:real('x').notNull(),z:real('z').notNull(),hidden:integer('hidden').notNull().default(0),created_at:integer('created_at').notNull(),updated_at:integer('updated_at').notNull()},t=>[uniqueIndex('bottles_id').on(t.id)]);
export const reports=sqliteTable('bottle_reports',{id:text('id').primaryKey(),bottle_id:text('bottle_id').notNull(),reporter:text('reporter').notNull(),created_at:integer('created_at').notNull()},t=>[uniqueIndex('report_unique').on(t.bottle_id,t.reporter)]);
export const runs=sqliteTable('race_runs',{id:text('id').primaryKey(),owner:text('owner').notNull(),created_at:integer('created_at').notNull(),completed_at:integer('completed_at'),time_ms:integer('time_ms'),penalties:integer('penalties').notNull().default(0),version:text('version').notNull()},t=>[index('runs_owner_time').on(t.owner,t.time_ms)]);

export const stamps=sqliteTable('event_stamps',{id:text('id').primaryKey(),owner:text('owner').notNull().references(()=>profiles.id),event_id:text('event_id').notNull(),source:text('source').notNull(),reference:text('reference').notNull(),created_at:integer('created_at').notNull()},t=>[uniqueIndex('stamp_owner_event').on(t.owner,t.event_id),uniqueIndex('stamp_reference').on(t.reference)]);
