import {mergeSea,missionMerge} from '../dist/planet/adventure.mjs';
import {moveBoat} from '../dist/planet/model.mjs';
import {REWARD_POINTS,COSTS,COURSE_VERSION,replayRace,normalisePoints} from '../dist/planet/expedition.mjs';
const json=(value,status=200)=>new Response(JSON.stringify(value),{status,headers:{'Content-Type':'application/json','Cache-Control':'no-store','X-Content-Type-Options':'nosniff'}});
const failure=(message,status=400)=>json({error:message},status);
const safeText=(v,max)=>typeof v==='string'?Array.from(v.trim()).slice(0,max).join(''):'';
const surveyValue=v=>{try{const d=typeof v==='string'?JSON.parse(v):v;return d&&typeof d==='object'?{seen:safeText(d.seen,200),favourite:safeText(d.favourite,100),next:safeText(d.next,100)}:null;}catch{return null;}};
const arr=v=>{try{const a=typeof v==='string'?JSON.parse(v):v;return Array.isArray(a)?a:[];}catch{return [];}};
const readProfile=(db,id)=>db.prepare('SELECT * FROM profiles WHERE id = ?').bind(id).first();
const object=v=>{try{const p=typeof v==='string'?JSON.parse(v):v;return p&&typeof p==='object'&&!Array.isArray(p)?p:{};}catch{return {};}};
const publicProfile=p=>({answers:arr(p.answers),avatar:p.avatar||'coral',mission:p.mission||'lost',seaLedger:object(p.sea_ledger),memberSince:p.created_at,id:p.public_id,nickname:p.nickname,genres:p.genres,artist:p.artist,memory:p.memory,message:p.message,survey:surveyValue(p.survey),color:p.color,flag:!!p.flag,trail:!!p.trail,model:p.model,accessory:!!p.accessory,points:p.points,coins:p.coins,owned:arr(p.owned),rewards:arr(p.rewards),discovered:arr(p.discovered),activeSeconds:p.active_seconds});
async function body(request,max=240000){const s=await request.text();if(s.length>max)throw Error('Request too large');return JSON.parse(s||'{}');}
function authId(request){return request.headers.get('oai-authenticated-user-id');}
function mutationAllowed(request){const origin=request.headers.get('origin'),url=new URL(request.url);return !origin||origin===url.origin;}
async function mutateProfile(db,id,fn){for(let n=0;n<3;n++){const raw=await readProfile(db,id);if(!raw)throw Error('Create a passport first');const p=publicProfile(raw);fn(p);normalisePoints(p);const now=Math.max(Date.now(),raw.updated_at+1);const res=await db.prepare('UPDATE profiles SET answers=?,avatar=?,mission=?,sea_ledger=?,nickname=?,genres=?,artist=?,memory=?,message=?,survey=?,color=?,flag=?,trail=?,model=?,accessory=?,owned=?,rewards=?,discovered=?,points=?,coins=?,active_seconds=?,updated_at=? WHERE id=? AND updated_at=?').bind(JSON.stringify(p.answers||[]),p.avatar||'coral',p.mission||'lost',JSON.stringify(p.seaLedger||{}),p.nickname,p.genres,p.artist,p.memory,p.message,p.survey?JSON.stringify(p.survey):null,p.color,p.flag?1:0,p.trail?1:0,p.model||'classic',p.accessory?1:0,JSON.stringify(p.owned),JSON.stringify(p.rewards),JSON.stringify(p.discovered),p.points,p.coins,p.activeSeconds,now,id,raw.updated_at).run();if(res.meta.changes)return p;}throw Error('Please try again');}
export async function api(request,env){const url=new URL(request.url),path=url.pathname.replace('/api/',''),method=request.method,id=authId(request);if(path==='session')return json({authenticated:!!id,profile:id&&env.DB?((p)=>p?publicProfile(p):null)(await readProfile(env.DB,id)):null,signIn:'/signin-with-chatgpt?return_to=%2Fplanet%2F%3Faccount%3D1'});if(!env.DB)return failure('Community service unavailable',503);
 const db=env.DB;if(method!=='GET'&&!mutationAllowed(request))return failure('Invalid origin',403);
 if(path==='leaderboard'&&method==='GET'){const race=url.searchParams.get('type')==='race';const sql=race?'SELECT p.public_id AS id,p.nickname,p.points,MIN(r.time_ms) AS timeMs FROM race_runs r JOIN profiles p ON p.id=r.owner WHERE r.completed_at IS NOT NULL AND r.version=? GROUP BY r.owner ORDER BY timeMs ASC LIMIT 100':'SELECT public_id AS id,nickname,points FROM profiles ORDER BY points DESC,created_at ASC LIMIT 100';const result=await (race?db.prepare(sql).bind(COURSE_VERSION):db.prepare(sql)).all();const rows=result.results.map((r,i)=>({...r,position:i+1}));let me=null;if(id){const profile=await readProfile(db,id);if(profile){if(race){const best=await db.prepare('SELECT MIN(time_ms) AS timeMs FROM race_runs WHERE owner=? AND version=? AND completed_at IS NOT NULL').bind(id,COURSE_VERSION).first();if(best?.timeMs){const faster=await db.prepare('SELECT COUNT(*) AS n FROM (SELECT MIN(time_ms) AS best FROM race_runs WHERE version=? AND completed_at IS NOT NULL GROUP BY owner HAVING best < ?)').bind(COURSE_VERSION,best.timeMs).first();me={id:profile.public_id,nickname:profile.nickname,timeMs:best.timeMs,position:faster.n+1};}}else{const better=await db.prepare('SELECT COUNT(*) AS n FROM profiles WHERE points>? OR (points=? AND created_at<?)').bind(profile.points,profile.points,profile.created_at).first();me={id:profile.public_id,nickname:profile.nickname,points:profile.points,position:better.n+1};}}}return json({rows,me});}
 if(path.startsWith('profiles/')&&method==='GET'){const p=await db.prepare('SELECT * FROM profiles WHERE public_id=?').bind(path.split('/')[1]).first();if(!p)return failure('Passport not found',404);const data=publicProfile(p);delete data.coins;delete data.discovered;delete data.owned;delete data.survey;delete data.seaLedger;data.stamps=(await db.prepare('SELECT event_id AS eventId,source,created_at AS createdAt FROM event_stamps WHERE owner=? ORDER BY created_at DESC').bind(p.id).all()).results;return json(data);}
 if(path==='bottles'&&method==='GET'){const result=await db.prepare('SELECT b.id,b.body,b.x,b.z,p.nickname,p.public_id AS profileId,b.updated_at AS updatedAt FROM bottles b JOIN profiles p ON p.id=b.owner WHERE b.hidden=0 ORDER BY b.updated_at DESC LIMIT 120').all();let own=null;if(id)own=await db.prepare('SELECT id,body,x,z,hidden FROM bottles WHERE owner=?').bind(id).first();return json({bottles:result.results,own});}

 if(path==='tickets/webhook'&&method==='POST'){
  if(!env.TICKET_WEBHOOK_SECRET)return failure('Ticket integration not configured',503);
  if(request.headers.get('authorization')!=='Bearer '+env.TICKET_WEBHOOK_SECRET)return failure('Invalid signature',401);
  try{const d=await body(request,3000);if(!['halloween','christmas','newyear'].includes(d.eventId)||!safeText(d.purchaseId,100))return failure('Invalid purchase');const p=await db.prepare('SELECT id FROM profiles WHERE public_id=?').bind(safeText(d.profileId,60)).first();if(!p)return failure('Member not found',404);await db.prepare('INSERT OR IGNORE INTO event_stamps(id,owner,event_id,source,reference,created_at) VALUES(?,?,?,?,?,?)').bind(crypto.randomUUID(),p.id,d.eventId,'purchase','purchase:'+safeText(d.purchaseId,100),Date.now()).run();return json({ok:true});}catch{return failure('Unable to process purchase',503);}
 }
 if(path==='stamps'&&method==='GET'){if(!id)return failure('Sign in to continue',401);return json({stamps:(await db.prepare('SELECT event_id AS eventId,source,created_at AS createdAt FROM event_stamps WHERE owner=? ORDER BY created_at DESC').bind(id).all()).results});}
 if(!id)return failure('Sign in to continue',401);
 try{
 if(path==='profile'&&method==='POST'){const data=await body(request,10000),nickname=safeText(data.nickname,24);if(!nickname)return failure('Nickname required');if(data.publicConsent!==true)return failure('Confirm your public profile');const now=Date.now();await db.prepare('INSERT OR IGNORE INTO profiles(id,nickname,public_id,created_at,updated_at) VALUES(?,?,?,?,?)').bind(id,nickname,crypto.randomUUID(),now,now).run();const result=await mutateProfile(db,id,p=>{p.nickname=nickname;p.answers=arr(data.answers).slice(0,5).map(v=>safeText(v,350));p.avatar=['coral','ocean','sand'].includes(data.avatar)?data.avatar:'coral';for(const [key,max] of [['genres',100],['artist',100],['memory',350],['message',200]])p[key]=safeText(data[key],max);});return json({profile:result});}
 if(path==='progress'&&method==='POST'){const data=await body(request,60000),existing=await readProfile(db,id);if(!existing)return failure('Create a passport first',409);const pointsKeys=arr(data.rewards).filter(k=>typeof k==='string'&&Object.hasOwn(REWARD_POINTS,k)&&!['first-race','bottle'].includes(k));const validNodes=new Set(['halloween','christmas','newyear','history','music','castaway','treasure','fiestera','christmas-discount','whatsapp','newyear-discount','gallery','lighthouse','shop','race','artists']);const result=await mutateProfile(db,id,p=>{p.rewards=[...new Set([...p.rewards,...pointsKeys])];p.seaLedger=mergeSea(p.seaLedger,data.seaLedger);p.mission=missionMerge(p.mission,data.mission);if(data.survey)p.survey=surveyValue(data.survey);p.discovered=[...new Set([...p.discovered,...arr(data.discovered).filter(x=>validNodes.has(x))])];normalisePoints(p);for(const item of arr(data.owned))if(Object.hasOwn(COSTS,item)&&!p.owned.includes(item)&&p.coins>=COSTS[item]){p.owned.push(item);normalisePoints(p);}if(/^#[a-f0-9]{6}$/i.test(data.color||''))p.color=data.color;p.flag=p.owned.includes('flag')&&!!data.flag;p.trail=p.owned.includes('trail')&&!!data.trail;p.model=p.owned.includes('model')&&data.model==='speedster'?'speedster':'classic';p.accessory=p.owned.includes('accessory')&&!!data.accessory;p.activeSeconds=Math.max(p.activeSeconds,Math.min(12000,Math.max(0,Number(data.activeSeconds)||0)));});return json({profile:result});}
 if(path==='bottles'&&['POST','DELETE'].includes(method)){if(!await readProfile(db,id))return failure('Create a passport first',409);if(method==='DELETE'){await db.prepare('DELETE FROM bottles WHERE owner=?').bind(id).run();return json({ok:true});}const data=await body(request,2000);const text=typeof data.body==='string'?data.body.trim():'';if(!text||Array.from(text).length>140)return failure('Use 1 to 140 characters');let x=Number(data.x),z=Number(data.z);if(!Number.isFinite(x)||!Number.isFinite(z)||Math.abs(x)>70||z>60||z< -290)return failure('Choose a position in the archipelago');const water=moveBoat({x,z,heading:0,vx:0,vz:0},{},0);x=water.x;z=water.z;const old=await db.prepare('SELECT id,hidden FROM bottles WHERE owner=?').bind(id).first();if(old?.hidden)return failure('This bottle is under review',403);const now=Date.now(),bottleId=old?.id||crypto.randomUUID();await db.prepare('INSERT INTO bottles(owner,id,body,x,z,created_at,updated_at) VALUES(?,?,?,?,?,?,?) ON CONFLICT(owner) DO UPDATE SET body=excluded.body,x=excluded.x,z=excluded.z,updated_at=excluded.updated_at').bind(id,bottleId,text,x,z,now,now).run();const profile=publicProfile(await readProfile(db,id));return json({ok:true,id:bottleId,profile});}
 if(path==='bottles/report'&&method==='POST'){const data=await body(request,1000),b=await db.prepare('SELECT id FROM bottles WHERE id=? AND hidden=0').bind(safeText(data.id,60)).first();if(!b)return failure('Bottle not found',404);await db.prepare('INSERT OR IGNORE INTO bottle_reports(id,bottle_id,reporter,created_at) VALUES(?,?,?,?)').bind(crypto.randomUUID(),b.id,id,Date.now()).run();await db.prepare('UPDATE bottles SET hidden=1 WHERE id=? AND (SELECT COUNT(*) FROM bottle_reports WHERE bottle_id=?)>=3').bind(b.id,b.id).run();return json({ok:true});}
 if(path==='stamps/redeem'&&method==='POST'){const d=await body(request,1000),codes=object(env.EVENT_STAMP_CODES),event=codes[safeText(d.code,100)];if(!env.EVENT_STAMP_CODES)return failure('Event codes are not active yet',503);if(!['halloween','christmas','newyear'].includes(event))return failure('Code not recognised');if(!await readProfile(db,id))return failure('Create your BOIA Card first',409);await db.prepare('INSERT OR IGNORE INTO event_stamps(id,owner,event_id,source,reference,created_at) VALUES(?,?,?,?,?,?)').bind(crypto.randomUUID(),id,event,'event-code','code:'+id+':'+event,Date.now()).run();return json({ok:true});}
 if(path==='race/start'&&method==='POST'){if(!await readProfile(db,id))return failure('Create a passport first',409);const now=Date.now(),runId=crypto.randomUUID();const recent=await db.prepare('SELECT COUNT(*) AS n FROM race_runs WHERE owner=? AND created_at>?').bind(id,now-60000).first();if(recent.n>=6)return failure('Please wait before starting another run',429);await db.prepare('INSERT INTO race_runs(id,owner,created_at,version) VALUES(?,?,?,?)').bind(runId,id,now,COURSE_VERSION).run();return json({id:runId});}
 if(path==='race/finish'&&method==='POST'){const data=await body(request),run=await db.prepare('SELECT * FROM race_runs WHERE id=? AND owner=?').bind(safeText(data.id,60),id).first();if(!run||run.version!==COURSE_VERSION)return failure('Run not found',404);if(run.completed_at!==null)return json({timeMs:run.time_ms,penalties:run.penalties,alreadySaved:true});const result=replayRace(data.commands);if(!result.valid||Date.now()-run.created_at<result.timeMs*.9||Date.now()-run.created_at>600000)return failure('Run could not be validated');const res=await db.prepare('UPDATE race_runs SET completed_at=?,time_ms=?,penalties=? WHERE id=? AND owner=? AND completed_at IS NULL').bind(Date.now(),result.timeMs,result.penalties,run.id,id).run();if(!res.meta.changes)return failure('Run already saved',409);const profile=await mutateProfile(db,id,p=>{if(!p.rewards.includes('first-race'))p.rewards.push('first-race');});return json({...result,profile});}
 return failure('Not found',404);
 }catch(error){console.warn('BOIA API',path,error.message);return failure(error.message==='Request too large'?error.message:'Unable to save. Please try again.',error.message==='Request too large'?413:503);}
}
